### ISSUE TITLE
Doesn't support target directory outside project directory

### ISSUE THREAD

**Issue by upsuper** [gnzlbg/cargo-asm#10] opened 2018-02-23 13:21 UTC
Cargo supports specifying a target directory somewhere other than `project/target` via `config`, like
```
[build]
target-dir = "/Users/upsuper/.cargo-target"
```

It seems with this config, `cargo asm` doesn't work. It reports
```
thread 'main' panicked at 'failed to iterate over the directory: project/target/release/deps: Error { depth: 0, inner: Io { path: Some("project/target/release/deps"), err: Error { repr: Os { code: 2, message: "No such file or directory" } } } }', src/libcore/result.rs:916:5
```

**Comment by gnzlbg** [comment] 2018-02-23 13:28
Thanks for reporting this, it is a known issue.

As a workaround you can use `--project-path` to specify a path.

The problem is that there is no way to ask `cargo` for the target directory, so... the tool currently does the following:

* when building the project, it parses the `--out-dir` of `rustc` invocations, and tries to find the assembly files there
* if the project is not build (e.g. because it has already been built), it looks in `target/{release,debug}/deps` and errors. 

I'll try to reproduce this locally and provide a better error message suggesting to use `--project-path`, and will try to figure out a way of obtaining this information from cargo without having to embed `cargo` into `cargo asm`.

**Comment by gnzlbg** [comment] 2018-02-23 13:44
@upsuper can you try with the `--clean` option and see if that works?

**Comment by upsuper** [comment] 2018-02-23 13:45
You mean `cargo asm some_lib::some_mod::some_func --rust --clean`?

**Comment by gnzlbg** [comment] 2018-02-23 13:46
Yes.

**Comment by upsuper** [comment] 2018-02-23 13:47
No it doesn't. It's still trying to look up things from `project/target` which still doesn't exist.

**Comment by upsuper** [comment] 2018-02-23 13:50
So I think you can use `cargo metadata` to get where the target directory is. Its output seems to include an item `target_directory` which points to my target directory.

**Comment by gnzlbg** [comment] 2018-02-23 13:53
So I think that's another bug. I've pushed a commit that should fix that. Could you try with the master branch?

**Comment by upsuper** [comment] 2018-02-23 14:01
It now reports
```
[ERROR]: could not find function at path "some_lib::some_mod::some_func" in the generated assembly.
Maybe you meant one of the following functions?


Otherwise make sure that the function is present in the final binary (e.g. if it's a generic function, make sure that it is actually monomorphized) or try to do a --clean build (sometimes changes are not picked up).
```

**Comment by gnzlbg** [comment] 2018-02-23 14:40
That's progress. I just improved that error message a bit and the latest master uses `cargo metadata` to obtain the target directory. Would you be able to test if this works correctly now? :)

**Comment by gnzlbg** [comment] 2018-02-24 09:04
@upsuper should have been fixed in the latest release which uses `cargo metadata` (I can't reproduce this anymore). Please let me know if it fixed it for you or not. Thanks for reporting this!

**Closed by gnzlbg** 2018-02-24 09:04 UTC

**Comment by upsuper** [comment] 2018-02-24 11:27
It seems that it works to some extent... although it doesn't work exactly as I expect, but that's probably a different issue...

**Comment by gnzlbg** [comment] 2018-02-24 12:05
@upsuper oh what happend?

**Comment by upsuper** [comment] 2018-02-24 12:09
I don't exactly know... basically I cannot see functions I try to see, probably because they are inlined?

**Comment by gnzlbg** [comment] 2018-02-24 12:10
if you just type the function name (without a path, e.g., for "crate::bar::foo" just type "foo"), are you getting suggestions?
